version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-api
    restart: unless-stopped  # always o'rniga unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s  # 10s o'rniga 30s
      timeout: 10s   # 5s o'rniga 10s
      retries: 3     # 5 o'rniga 3
    environment:
      - DATABASE_URL=postgresql://postgres:3636@postgres:5432/lms_db
      - NODE_ENV=production
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgresprisma
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3636
      POSTGRES_DB: lms_db
    restart: unless-stopped
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: nest-prisma-docker-db
  redis-data:
    name: redis-data